# Generated by Django 3.1.2 on 2020-11-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
