# Generated by Django 3.1.2 on 2020-11-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_content',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
