# Generated by Django 3.1.2 on 2020-11-15 11:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None)),
                ('purpose', models.CharField(choices=[('tc', 'Tăng cơ'), ('gm', 'Giảm mỡ'), ('sk', 'Duy trì sức khỏe')], max_length=100)),
                ('time_register', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
