# Generated by Django 3.1.2 on 2020-11-17 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_register_time_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 17, 14, 54, 8, 601072), max_length=100),
        ),
    ]
