# Generated by Django 3.1.2 on 2020-11-17 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201117_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 17, 15, 58, 40, 319154), max_length=100),
        ),
    ]
