# Generated by Django 3.1.2 on 2020-11-17 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201117_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 17, 16, 49, 50, 557336), max_length=100),
        ),
    ]
