# Generated by Django 3.1.2 on 2020-11-18 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20201117_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 18, 14, 15, 35, 545572), max_length=100),
        ),
    ]
