# Generated by Django 3.1.2 on 2020-11-18 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20201118_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 18, 14, 30, 5, 966848), max_length=100),
        ),
    ]
