# Generated by Django 3.1.2 on 2020-11-18 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20201118_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 18, 18, 12, 51, 231537), max_length=100),
        ),
    ]
