# Generated by Django 3.1.2 on 2020-11-19 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20201119_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 19, 16, 6, 10, 956454), max_length=100),
        ),
    ]
