# Generated by Django 3.1.2 on 2020-11-20 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20201119_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 20, 16, 5, 49, 293476), max_length=100),
        ),
    ]
