# Generated by Django 3.1.2 on 2020-11-23 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20201120_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 23, 14, 54, 43, 821570), max_length=100),
        ),
    ]
