# Generated by Django 3.1.2 on 2020-11-23 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20201123_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 23, 15, 17, 35, 622648), max_length=100),
        ),
    ]
