# Generated by Django 3.1.2 on 2020-11-25 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20201125_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 11, 25, 19, 58, 50, 782666), max_length=100),
        ),
    ]
