# Generated by Django 3.1.2 on 2021-12-02 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20201125_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='purpose',
            field=models.CharField(choices=[('', 'Mục tiêu tập luyện'), ('tc', 'Tăng cơ'), ('gm', 'Giảm mỡ'), ('sk', 'Duy trì sức khỏe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='time_register',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 12, 2, 14, 55, 57, 600536), max_length=100),
        ),
    ]
